use serde_json::Value;

/// Calculates the maximum rate of change (peak derivative) of a keyframe track.
/// Takes into account the derivative of interpolation curves (linear = 1.0, easeInOut = 1.5, easeIn/easeOut = 3.0).
pub fn calculate_track_peak_rate(raw_keyframes: &[Value], fps: f64, value_scale: f64) -> f64 {
    if raw_keyframes.len() <= 1 {
        return 0.0;
    }

    struct KfSample {
        time_sec: f64,
        value: f64,
        easing: String,
    }

    let mut list: Vec<KfSample> = raw_keyframes
        .iter()
        .filter_map(|k| {
            let frame = k.get("frame").and_then(|v| v.as_i64())?;
            let val = k.get("value").and_then(|v| v.as_f64())?;
            let easing = k
                .get("easing")
                .and_then(|v| v.as_str())
                .unwrap_or("linear")
                .to_string();
            Some(KfSample {
                time_sec: frame as f64 / fps,
                value: val * value_scale,
                easing,
            })
        })
        .collect();

    if list.len() <= 1 {
        return 0.0;
    }

    list.sort_by(|a, b| a.time_sec.partial_cmp(&b.time_sec).unwrap_or(std::cmp::Ordering::Equal));

    let mut peak_velocity = 0.0;

    for i in 0..list.len() - 1 {
        let span = (list[i + 1].time_sec - list[i].time_sec).abs();
        if span < 0.0001 {
            continue;
        }
        let delta_val = (list[i + 1].value - list[i].value).abs();
        let avg_rate = delta_val / span;

        // Multiplier of the maximum derivative of the interpolation curve:
        // - Linear: 1.0 (constant speed)
        // - EaseInOut (Cubic smoothstep 3u^2 - 2u^3): maximum derivative is 1.5 at u = 0.5
        // - EaseIn / EaseOut (Cubic u^3 / 1-(1-u)^3): maximum derivative is 3.0 at u = 1 / u = 0
        let easing_factor = match list[i].easing.as_str() {
            "easeInOut" => 1.5,
            "easeIn" | "easeOut" => 3.0,
            _ => 1.0,
        };

        let seg_peak = avg_rate * easing_factor;
        if seg_peak > peak_velocity {
            peak_velocity = seg_peak;
        }
    }

    peak_velocity
}

/// Calculates the maximum kinetic velocity (in pixels per second on the export canvas)
/// generated by position, rotation, and scale keyframe interpolations.
pub fn calculate_clip_max_velocity(
    plugin_data: Option<&Value>,
    project_fps: f64,
    scale_x: f64,
    scale_y: f64,
    canvas_w: f64,
    canvas_h: f64,
) -> f64 {
    let fps = if project_fps > 0.0 { project_fps } else { 30.0 };

    let mut max_vx = 0.0;
    let mut max_vy = 0.0;
    let mut max_vrot = 0.0;

    // 1. X translation velocity
    if let Some(track) = super::track_reader::get_keyframe_track(plugin_data, "positionXTrack") {
        if track.get("enabled").and_then(|v| v.as_bool()).unwrap_or(true) {
            if let Some(kfs) = track.get("keyframes").and_then(|v| v.as_array()) {
                max_vx = calculate_track_peak_rate(kfs, fps, scale_x);
            }
        }
    }

    // 2. Y translation velocity
    if let Some(track) = super::track_reader::get_keyframe_track(plugin_data, "positionYTrack") {
        if track.get("enabled").and_then(|v| v.as_bool()).unwrap_or(true) {
            if let Some(kfs) = track.get("keyframes").and_then(|v| v.as_array()) {
                max_vy = calculate_track_peak_rate(kfs, fps, scale_y);
            }
        }
    }

    // 3. Rotational velocity (outermost vertices and edges)
    let r_corner = 0.5 * canvas_w.hypot(canvas_h);
    if let Some(track) = super::track_reader::get_keyframe_track(plugin_data, "rotationTrack") {
        if track.get("enabled").and_then(|v| v.as_bool()).unwrap_or(true) {
            if let Some(kfs) = track.get("keyframes").and_then(|v| v.as_array()) {
                let deg_per_sec = calculate_track_peak_rate(kfs, fps, 1.0);
                let rad_per_sec = deg_per_sec * std::f64::consts::PI / 180.0;
                max_vrot = rad_per_sec * r_corner;
            }
        }
    }

    // 4. Scale expansion velocity
    let max_dim = canvas_w.max(canvas_h);
    let mut max_s_rate = 0.0;
    for track_name in ["scaleXTrack", "scaleYTrack"] {
        if let Some(track) = super::track_reader::get_keyframe_track(plugin_data, track_name) {
            if track.get("enabled").and_then(|v| v.as_bool()).unwrap_or(true) {
                if let Some(kfs) = track.get("keyframes").and_then(|v| v.as_array()) {
                    let s_rate = calculate_track_peak_rate(kfs, fps, 1.0);
                    if s_rate > max_s_rate {
                        max_s_rate = s_rate;
                    }
                }
            }
        }
    }
    let max_vscale = max_s_rate * (max_dim * 0.5);

    let v_trans = max_vx.hypot(max_vy);
    v_trans + max_vrot + max_vscale
}

/// Determines the temporal supersampling factor (K) based on maximum kinetic velocity
pub fn compute_adaptive_supersample_factor(max_velocity: f64, export_fps: f64) -> u32 {
    if export_fps >= 60.0 {
        if max_velocity >= 1800.0 {
            return 2;
        }
        return 1;
    }

    if max_velocity < 20.0 {
        1 // Tier 0: Static or micro-motion (< 20 px/s) -> 1x (24 FPS, zero additional cost, 100% sharp)
    } else if max_velocity < 150.0 {
        2 // Tier 1: Ken Burns / Subtle motion (20-150 px/s) -> 2x (48 FPS)
    } else if max_velocity < 600.0 {
        4 // Tier 2: Moderate motion (150-600 px/s) -> 4x (96 FPS)
    } else if max_velocity < 1800.0 {
        8 // Tier 3: Fast motion / Swipe (600-1800 px/s) -> 8x (192 FPS)
    } else {
        16 // Tier 4: Hypersonic / Whip-pan / Snap (> 1800 px/s) -> 16x (384 FPS)
    }
}

/// Generates cinematic shutter weight distribution for FFmpeg's tmix filter
pub fn generate_shutter_weights(factor: u32) -> String {
    match factor {
        1 => "1".to_string(),
        2 => "1 1".to_string(),
        4 => "1 2 2 1".to_string(), // 180° smooth bell weighting
        8 => "1 2 4 8 8 4 2 1".to_string(), // Gaussian-like photographic shutter
        16 => "1 1 2 3 5 8 13 16 16 13 8 5 3 2 1 1".to_string(), // Natural optical blur
        n => vec!["1"; n as usize].join(" "),
    }
}
